---
trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  HUGO_VERSION: 0.55.6
  HUGO_BINARY: hugo_$(HUGO_VERSION)_Linux-64bit.deb

stages:
  - stage: Build
    jobs:
      - job: Linux
        steps:
          - checkout: self
            clean: all
            submodules: true

          - script: |
              wget https://github.com/spf13/hugo/releases/download/v$(HUGO_VERSION)/$(HUGO_BINARY) /tmp/hugo.deb
              sudo dpkg -i /tmp/hugo.deb
              hugo version