---
trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

stages:
  - stage: Build
    jobs:
      - job: Linux
        steps:
          - checkout: self
            clean: all
            submodules: true

          - script: echo "hoi"