---
trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  HUGO_VERSION: 0.55.6
  HUGO_BINARY: hugo_$(HUGO_VERSION)_Linux-64bit.deb

stages:
  - stage: Build
    jobs:
      - job: Install
        steps:
          - bash: |
              wget -P /tmp https://github.com/spf13/hugo/releases/download/v$(HUGO_VERSION)/$(HUGO_BINARY) 
              sudo dpkg -i /tmp/$(HUGO_BINARY)
              hugo version

      - job: Generate
        steps:
          - checkout: self
            clean: all
            submodules: true

          - bash: |
              hugo --minify -b "https://cloudnative.amsterdam" --cleanDestinationDir -d $(Build.ArtifactStagingDirectory)

          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: 'hugo-site'
              targetPath: $(Build.ArtifactStagingDirectory)