# publishDir = "docs"

baseURL = "https://competent-nightingale-85ae87.netlify.com/"
languageCode = "en"
title = "QCrypt 2020"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

GoogleAnalytics = "UA-23222525-2"

[params]
    title = "QCrypt 2020"
    date = "2020-08-10"
    description = "10th International Conference on Quantum Cryptography, held in Amsterdam, The Netherlands, 10-14 August 2020"
    images = ["/images/social-share.jpg"]
    email = "2020@qcrypt.net"
    keywords = "event, quantum cryptography, QCrypt, Amsterdam"
    copyright = "We :heart: sheep"
    copyright_link = "https://github.com/QCrypt/public-website"
    # cfpUrl = ""
    # subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#086788"

[params.logos]
    jumbo = "/images/logos/QCr_Logo.png"
    header = "/images/logos/QCr_Logo.png"
    footer = "/images/logos/netlify-color-accent.svg"
    footer_link = "https://www.netlify.com"

#[menu]
#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = true

[languages]
[languages.en]
    weight = 1
    languageName = "us"

[taxonomies]
    tag = "tags"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = false
